config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dashboard' => 'accounts#index'
  get '/profile/:username' => 'accounts#profile', as: :profile
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  post 'follow/account' => 'accounts#follow_account', as: :follow_account
  delete 'unfollow/:account_id' => 'accounts#unfollow_account', as: :unfollow_account

  # get 'post/:id' => 'posts#show', as: :post

  resources :posts, only: %i[new create show]
  resources :comments, only: %i[create destroy]

  root to: 'public#homepage'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ImageUploader::Attachment(:image)

  validates_uniqueness_of :username, :email

  has_many :posts
  has_many :likes
  # belongs_to :follower, foreign_key: :follower_id, class_name: "Account"
  # belongs_to :following, foreign_key: :following_id, class_name: "Account"

  def full_name
    "#{first_name} #{last_name}"
  end

  def all_followings
    following_ids = Follower.where(follower_id: self.id).map(&:following_id)

    Account.where(id: following_ids)
  end

  def all_followers
    followers_ids = Follower.where(following_id: self.id).map(&:follower_id)

    Account.where(id: followers_ids)
  end

  def total_followers
    Follower.where(following_id: id).count
  end

  def total_following
    Follower.where(follower_id: id).count
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :comment, :account_id, :post_id

  attr_accessor :return_to
end

app/models/follower.rb
# frozen_string_literal: true

class Follower < ApplicationRecord
  # has_and_belongs_to_ many :accounts
  belongs_to :follower, foreign_key: :follower_id, class_name: 'Account'

  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_uniqueness_of :post_id, scope: :account_id

  after_create :increase_post_like_counter
  after_destroy :decrease_post_like_counter

  private

  def increase_post_like_counter
    Post.find(post_id).increment(:total_likes_count).save
  end

  # def increase_post_like_counter
  #   post = Post.find(self.post_id)
  #   if post.total_likes_count == nil
  #     post.total_likes_count = Like.where(post_id: post.id).count
  #   end
  #   increment(:total_likes_count).save
  # end

  def decrease_post_like_counter
    Post.find(post_id).decrement(:total_likes_count).save
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  include ImageUploader::Attachment(:image)
  belongs_to :account

  has_many :likes
  has_many :comments

  before_create :set_active

  scope :active, -> { where active: true }

  def set_active
    self.active = true
    self.total_likes_count = 0
    self.total_comments_count = 0
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:profile]

  def index
    # user feed
    # followers_ids = Follower.where(follower_id: current_account.id).map(&:follower_id)
    # followers_ids << current_account.id

    @posts = Post.active.limit 50
    @comment = Comment.new
  end

  def follow_account
    following_account_id = params[:follow_id]
    if Follower.create!(follower_id: current_account.id, following_id: following_account_id)
      flash[:success] = 'New following'
    else
      flash[:danger] = 'Fail'
    end
  end

  def unfollow_account
    account_id = params[:account_id]
    follow = Follower.where(following_id: account_id, follower_id: current_account.id)
    if follow.destroy_all
      flash[:success] = 'New following'
    else
      flash[:danger] = 'Fail'
    end
  end

  def profile
    @posts = @account.posts.active
  end

  def set_account
    @account = Account.find_by_username(params[:username])
  end



  private

  def update_follower_suggestion; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update, keys: %i[username first_name last_name email description website image password]
    )
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[username first_name last_name email description website image_data password]
    )
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_account!

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?

    if @comment.save
      redirect_to dashboard_path
    else
      redirect_to new_posts_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_account!

  def save_like
    @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
    @post_id = params[:post_id]
    existing_like = Like.where(post_id: params[:post_id], account_id: current_account.id)

    respond_to do |format|
      format.js do
        if existing_like.any?
          existing_like.first.destroy
          @success = false
        elsif @like.save
          @success = true
        else
          @success = false
        end

        @post_likes = Post.find(@post_id).total_likes_count
        render 'posts/like'
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_post, only: [:show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    if @post.save
      redirect_to dashboard_path, flash: { success: 'Post was created successfully!' }
    else
      redirect_to new_posts_path, flash: { success: 'Post was not saved!' }
    end
  end

  def show
    @comment = Comment.new
  end

  private

  def set_post
    @post = Post.find(params[:id]) if params[:id].present?
  end

  def post_params
    params.require(:post).permit(:image, :cached_image_data, :description)
  end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ApplicationController
  def homepage; end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
  def profile_picture(account, size)
    image_tag(account.image_url, width: size, height: size, class: 'imx-auto d-block rounded-circle')
  end

  def can_edit_profile?(profile_id)
    account_signed_in? && current_account.id == profile_id
  end

  def follower_suggestion
    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id

    Account.where.not(id: following_ids)
  end


end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_liked_by_user?(post_id)
    Like.where(post_id: post_id, account_id: current_account.id).any?
  end
end

app/helpers/public_helper.rb
# frozen_string_literal: true

module PublicHelper
end

app/views/accounts/_follower_suggestion.html.erb
<% @follower_suggestion.each do |user| %>
  <div class="recommended-follower">
    <div class="row fs-5">
      <%= render "username", account: user, size: 30 %>
      <div class="col text-end" style="margin: auto">
        <%=form_tag follow_account_path, method: :post do %>
          <%= hidden_field_tag :follow_id, user.id %>
          <%= submit_tag "Follow", class: "btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>
  </div><br>
<% end %>

app/views/accounts/_followers.html.erb
<% followers.each do |user| %>
  <div class="recommended-follower">
    <div class="row fs-5">
      <%= render "username", account: user, size: 30 %>
      <div class="col text-end" style="margin: auto">
        <%=form_tag follow_account_path, method: :post do %>
          <%= hidden_field_tag :follow_id, user.id %>
          <%= submit_tag "Follow", class: "btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>
  </div><br>
<% end %>

app/views/accounts/_username.html.erb
<div class="col-sm-auto my-auto pe-0">
  <%= link_to profile_picture(account, size), profile_path(account.username) %>
</div>
<div class="col-sm-auto ps-1" style="margin-top: auto; margin-bottom: auto">
  <%= link_to account.username, profile_path(account.username), class: "text-start text-dark text-decoration-none" %>
</div>

app/views/accounts/index.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col-8">
      <% @posts.each do |post| %>
        <div class="card">

          <div class="card-header">
            <div class="row fs-4">
              <%= render "username", account: post.account, size: 50 %>
              <div class="col" style="margin: auto">
                <h5 class="text-muted text-end">created at <%= post.created_at %></h5>
              </div>
            </div>
          </div>

          <%= image_tag post.image_url, class: "img" %>

          <div class="card-footer bg-transparent text-start">
            <div class="post-action">
              <i class="fa-heart like-<%= post.id %> <%= post_liked_by_user?(post.id)? 'active fa': 'far'%> fa-2x post-like" data-id="<%= post.id %>"></i>
              <%= link_to post_path(post.id) do %>
                <i class="far fa-comment fa-2x post-comment"></i>
              <% end %>
            </div>

            <p><strong id="post-<%= post.id %>-likes"><%= post.total_likes_count %> likes</strong></p>

            <div class="row row-cols-auto">
              <p><strong><%= link_to post.account.username, profile_path(post.account.username), class: "text text-dark text-decoration-none" %></strong></p>
              <%= simple_format post.description %>
            </div>

            <%= render "posts/comments", post: post %>

            <p class="card-text"><small class="text-muted"><%= time_ago_in_words post.updated_at %></small></p>
            <%= form_for @comment do |f| %>
              <div class="row">
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control col mx-1", id:"comment-post-#{post.id}" %>
                <%= f.submit "Send", class: "btn btn-outline-secondary float-right col-2  mx-1"%>
              </div>
            <% end %>
          </div>

        </div><br>
      <% end %>
    </div>

    <div class="col-4">
      <div class="account-summary"  >
        <div class="row fs-4">
          <%= render "username", account: current_account, size: 50 %>
        </div><br />
        <div class="row">
          <div class="card">
            <div class="card-body">
              <div class="row row-cols-2">
                <p class="text-muted">Suggestion for you</p>
                <%#= link_to "View All", "#", class: "float-right text-dark text-end" %>
              </div>
              <%= render "accounts/followers", followers: follower_suggestion %>
            </div>
          </div>
        </div><br />

      </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container" style="min-width: 1000px">
  <br>
  <div class="row">
    <div class="col-4">
      <%= image_tag @account.image_url, width: "250px", height: "250px", class: "imx-auto d-block rounded-circle" %>
    </div>
    <div class="col-8 text-start" style="margin: auto">
      <div class="row row-cols-auto">
        <div class="col"><h1><%= @account.username %></h1></div>
        <div class="col mx-auto"><%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-muted" if can_edit_profile? @account.id %></div>
      </div>
      <div class="row row-cols-auto">
          <div class="col"><%= @account.posts.count %> posts</div>
          <div class="col" type="button" data-bs-toggle="modal" data-bs-target="#followers"><%= @account.total_followers %> followers</div>
          <div class="col" type="button" data-bs-toggle="modal" data-bs-target="#following"><%= @account.total_following %> following</div>
      </div>
      <p><%= @account.full_name %></p>
      <%= simple_format @account.description %>

      <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <div class="row row-cols-3">
        <% @posts.each do |post| %>
          <%= link_to post_path(post.id) do %>
            <div class="col picture m-2" style="width: 400px; height: 400px">
              <%= image_tag post.image_url %>
          </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="following" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Followings</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @account.all_followings.each do |account|  %>
          <div class="row fs-4">
            <%= render "username", account: account, size: 25 %>
            <div class="col text-end">
              <%= link_to "Unfollow", unfollow_account_path(account), method: :delete, class: "btn btn-outline-secondary" if @account.id == current_account.id %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="followers" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Followers</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @account.all_followers.each do |account|  %>
          <div class="row fs-4">
            <%= render "username", account: account, size: 25 %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item">
  <% if current_page?(dashboard_path) %>
    <%= link_to "Home", dashboard_path, class: "nav-link active" %>
  <% else %>
    <%= link_to "Home", dashboard_path, class: "nav-link" %>
  <% end %>
</li>
<li class="nav-item">
  <% if current_page?(new_post_path) %>
    <%= link_to "New Post", new_post_path, class: "nav-link active" %>
  <% else %>
    <%= link_to "New Post", new_post_path, class: "nav-link" %>
  <% end %>
</li>
<li class="nav-item">
  <% if current_page?(profile_path(current_account.username)) %>
    <%= link_to "Profile", profile_path(current_account.username), class: "nav-link active" %>
  <% else %>
    <%= link_to "Profile", profile_path(current_account.username), class: "nav-link" %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/_public_nav.html.erb
<!--<li class="nav-item">-->
<!--  <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--</li>-->
<li class="nav-item">
  <% if current_page?(new_account_registration_path) %>
    <%= link_to "Sign up", new_account_registration_path, class: "nav-link active"%>
  <% else %>
    <%= link_to "Sign up", new_account_registration_path, class: "nav-link"%>
  <% end %>
</li>
<li class="nav-item">
  <% if current_page?(new_account_session_path) %>
    <%= link_to "Sign in", new_account_session_path, class: "nav-link active" %>
  <% else %>
    <%= link_to "Sign in", new_account_session_path, class: "nav-link" %>
  <% end %>
</li>

<!--<li class="nav-item">-->
<!--  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--</li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/42a7141eb1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-sm navbar navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Stogram</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="d-flex">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if account_signed_in? %>
              <%= render "layouts/account_nav" %>
            <% else %>
              <%= render "layouts/public_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav><br><br>

  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
  <div class="row">
  <%= render "accounts/username", account: comment.account, size: 30 %>
<!--  <strong><%#= comment.account.username %></strong>-->
  </div>
    <p><%= comment.comment %></p>

<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="text-start">

    <div class="form-group">
      <%= f.label :image %><br />
      <%= f.hidden_field :image %>
      <%= f.file_field :image, class: "form-control"%>
    </div><br />

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, class: "form-control"%>
    </div><br />

    <%= f.submit "Save", class: "btn btn-success"%>
  </div>
<% end %>

app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").removeClass("far");
$(".like-<%= @post_id %>").addClass("active");
$(".like-<%= @post_id %>").addClass("fa");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
$(".like-<%= @post_id %>").removeClass("fa");
$(".like-<%= @post_id %>").addClass("far");
<% end %>
$("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<br>
<h2>New Post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="container t">
  <br>
  <div class="row justify-content-md-center" >
    <div class="col picture">
      <%= image_tag @post.image_url, class: "" %>
    </div>
    <div class="col px-0 border" style="min-width: 300px">
      <div class="py-2  ms-2">
        <div class="row fs-4 pe-2">
          <%= render "accounts/username", account: @post.account, size: 50 %>
          <div class="col" style="margin: auto">
            <h5 class="text-muted text-end m-auto me-0"><%= @post.created_at %></h5>
          </div>
        </div>
      </div>
      <div class="card-footer bg-transparent text-start">

        <div class="row row-cols-auto">
          <p><strong><%= link_to @post.account.username, profile_path(@post.account.username), class: "text text-dark text-decoration-none" %></strong></p>
          <%= simple_format @post.description %>
        </div>
        <%= render "posts/comments", post: @post %>

        <div class="m-auto align-items-center text-center row post-action">
          <i class="fa-heart like-<%= @post.id %> <%= post_liked_by_user?(@post.id)? 'active fa': 'far'%> fa-2x post-like" data-id="<%= @post.id %>"></i>
          <strong class="text-center m-auto" id="post-<%= @post.id %>-likes"><%= @post.total_likes_count %> likes</strong>
          <small class="text-muted"><%= time_ago_in_words @post.updated_at %></small>
        </div>



        <%= form_for @comment do |f| %>
          <div class="row">
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control col mx-1" %>
            <%= f.submit "Send", class: "btn btn-outline-secondary float-right col-2  mx-1"%>
          </div>
        <% end %>
        </div>
      </div>

    </div>
  </div>

</div>